categories:
  experimental:
    - pernikove koreni
    - skorice mleta
    - hladka mouka
    - maslo
    - domaci med ve sklenici
    - honey in a jar
    - cukr moučka
    - kyprici prasek
  staples:
    - flour
    - salt
    - sugar
    - pepper
    - parchment paper
    - potato starch
    - cooking spray
    - cornmeal
    - baking soda

  vegetables:
    - carrot
    - parsnips
    - potato
    - tomato
    - jalapeño
    - red onion
    - white onion
    - onion
    - chives
    - cucumber
    - bell pepper
    - red pepper
    - green pepper
    - broccoli
    - cauliflower
    - zucchini
    - leek
    - red cabbage
    - spinach
    - kale
    - lettuce
    - eggplant
    - celery
    - asparagus
    - mushroom
    - garlic
    - ginger
    - shallot
    - turnip
    - radish
    - beet
    - sweet potato
    - green bean
    - peas
    - chile
    - scallions
    - avocado
    - fennel
    - green olive
    - black olive
    - olive
    - butternut squash
    - pickle
    - argula
    - horseradish
  broths:
    - chicken broth
    - beef broth
    - vegetable broth
    - dashi
  pasta_and_stuff:
    - egg noodles
    - spaghetti
    - bread
    - breadcrumbs
    - pasta
    - lasagna sheets
    - linguine
    - fettuccine
    - rice
    - couscous
    - quinoa
    - tortillas
    - naan
    - pita
    - sourdough bread
    - baguette
    - brioche
    - rye bread
  proteins:
    - egg
    - tofu
    - soya
    - prosciutto
    - bratwurst
    - chicken
    - chicken breast
    - chicken thigh
    - beef
    - pork
    - lamb
    - turkey
    - duck
    - crab
    - crabmeat
    - venison
    - bacon
    - sausage
    - ham
    - prosciutto
    - salami
    - pastrami
  fish:
    - red snapper
    - mahi-mahi
    - halibut
    - anchovy
    - anchovies
    - salmon
  dairy:
    - milk
    - cream
    - buttermilk
    - yogurt
    - greek yogurt
    - sour cream
    - roquefort
    - cream cheese
    - cheddar
    - mozzarella
    - parmesan
    - Parmigiano-Reggiano
    - ricotta
    - gouda
    - brie
    - feta
    - blue cheese
    - cottage cheese
    - cheese
    - butter
  spices:
    - vanilla
    - cumin
    - black pepper
    - turmeric
    - paprika
    - anise seeds
    - star anise
    - chili powder
    - cayenne
    - curry powder
    - cinnamon

    - nutmeg
    - cloves
    - fennel seeds
    - cardamom
    - saffron
    - sage
    - allspice
    - curry paste
  herbs:
    - mint
    - cilantro
    - tarragon
    - parsley
    - basil
    - thyme
    - rosemary
    - bay leaf
    - dill
    - coriander
    - oregano
  fruits:
    - lemon
    - acorn
    - lime
    - orange
    - apple
    - banana
    - pineapple
    - mango
    - pear
    - peach
    - cherry
    - grape
    - strawberry
    - blueberry
    - raspberry
    - watermelon
    - cantaloupe
    - kiwi
    - pomegranate
    - kumquat
  condiments:
    - vanilla extract
    - cocoa powder
    - dry yeast
    - lard
    - sesame seeds
    - olive oil
    - vegetable oil
    - salt
    - black pepper
    - white pepper
    - apple cider vinegar
    - sugar
    - soy sauce
    - mustard
    - mayonnaise
    - ketchup
    - hot sauce
    - chili sauce
    - barbecue sauce
    - worcestershire sauce
    - teriyaki sauce
    - fish sauce
    - hoisin sauce
    - sesame oil
    - sriracha
    - honey

    - chocolate
    - vinegar
    - tahini
    - pesto
  liquids:
    - brandy
    - white wine
    - red wine
    - wine
    - whiskey
    - vodka
    - beer
    - lager
    - coffee
    - water
    - liquor
  nuts:
    - peanut
    - almond
    - walnut