apple: apple
apple cider vinegar: vinegar
asparagus: asparagus
avocado: avocado
bacon: bacon
baguette: baguette
baking soda: baking soda
balkansky syr: feta
banana: banana
barbecue sauce: barbecue sauce
basil: basil
bay leaf: bay leaf
bbq omacka: barbecue sauce
beef: beef
beer: beer
beet: beet
bell pepper: bell pepper
black olive: olive
black pepper: black pepper
blue cheese: blue cheese
blueberry: blueberry
bottle of water: water
bramborovy skrob: starch
branik: beer
bread: bread
brie: brie
broccoli: broccoli
butter: butter
buttermilk: buttermilk
butternut squash: butternut squash
cabbage: cabbage
camembert: brie
cantaloupe: cantaloupe
carrot: carrot
cauliflower: cauliflower
celery: celery
cerny pepr: black pepper
champinon: mushroom
cheddar: cheddar
cheese: cheese
cherry: cherry
chicken breast: chicken
chicken thigh: chicken
chili sauce: hot sauce
chilli: chilli
chilli omacka: hot sauce
chilli powder: chilli
chocolate: chocolate
cilantro: cilantro
cinnamon: cinnamon
cloves: cloves
cocoa powder: cocoa powder
coconut: coconut
coconut milk: coconut milk
coconut milk in a can: coconut milk
cod: cod
coffee beans: coffee
cokolada: chocolate
corn starch: starch
cottage: cottage cheese
cottage cheese: cottage cheese
cream cheese: cream cheese
cucumber: cucumber
cukr: sugar
cukr krystal: sugar
cukr moucka: sugar
cumin: cumin
curry powder: curry powder
dill: dill
egg: egg
eggplant: eggplant
feta: feta
flour: flour
garlic: garlic
ginger: ginger
gouda: gouda
grape: grape
greek yogurt: yogurt
green bell pepper: bell pepper
green olive: olive
ground black pepper: black pepper
ground oregano: oregano
ground paprika: paprika
ham: ham
hermelin: brie
hladka mouka: flour
honey: honey
honey in a jar: honey
horcice: mustard
horseradish: horseradish
hot sauce: hot sauce
hruba mouka: flour
jablecny ocet: vinegar
jacobs: coffee
"jalape\xF1o": "jalape\xF1o"
jedla soda: baking soda
jogurt: yogurt
jug of milk: milk
kakao: cocoa powder
kecup: ketchup
ketchup: ketchup
kikkoman: soy sauce
kiwi: kiwi
kokosove mleko: coconut milk
kukuricny skrob: starch
kyprici prasek: baking powder
lager: beer
lavazza: coffee
leek: leek
lemon: lemon
lettuce: lettuce
lime: lime
majoneza: mayonnaise
mango: mango
maslo: butter
mayonnaise: mayonnaise
med: honey
milk in a carton: milk
mozzarella: mozzarella
mushroom: mushroom
mustard: mustard
naan: naan
nakladane okurky: pickles
niva: blue cheese
nutmeg: nutmeg
ocet: vinegar
olive oil: olive oil
olivovy olej: olive oil
onion: onion
orange: orange
oregano: oregano
packed egg noodles: egg noodles
paprika uzena: paprika
parmesan: parmesan
parsley: parsley
pasta: pasta
peach: peach
pear: pear
peas: peas
pernikove koreni: gingerbread spice
pesto: pesto
philadelphia: cream cheese
pickles: pickles
pilsner urquell: beer
pineapple: pineapple
pita: pita
pivo: beer
plnotucne mleko: milk
podmasli: buttermilk
polohruba mouka: flour
polotucne mleko: milk
pomegranate: pomegranate
potato: potato
potato starch: starch
prasek do peciva: baking powder
prosciutto: prosciutto
radish: radish
raspberry: raspberry
raw beef: beef
raw chicken: chicken
raw cod meat: cod
raw pork: pork
raw pork chop: pork
raw pork meat: pork
raw salmon meat: salmon
raw trout meat: trout
raw tuna meat: tuna
recky jogurt: yogurt
red bell pepper: bell pepper
red onion: red onion
red wine: red wine
repkovy olej: vegetable oil
rice: rice
ricotta: ricotta
rosemary: rosemary
salami: salami
salmon: salmon
sausage: sausage
scallions: scallions
shallot: shallot
skorice mleta: cinnamon
slunecnicovy olej: vegetable oil
smetana na slehani: cream
smetana na vareni: cream
sourdough bread: bread
soy sauce: soy sauce
spaghetti: pasta
spinach: spinach
sriracha: hot sauce
strawberry: strawberry
sugar: sugar
sunka: ham
sunka od kosti: ham
sweet potato: sweet potato
tabasco: hot sauce
tesco maslo: butter
thyme: thyme
tofu: tofu
tomato: tomato
tortillas: tortillas
trout: trout
tuna: tuna
vanilla: vanilla
vegetable oil: vegetable oil
vejce M: egg
vinegar: vinegar
vitana bazalka: basil
vitana bobkovy list: bay leaf
vitana cerny pepr: black pepper
vitana chilli mlete: chilli
vitana kari: curry powder
vitana kmin: cumin
vitana kopr: dill
vitana muskatovy orech: nutmeg
vitana oregano: oregano
vitana paprika sladka: paprika
vitana provencalske bylinky: provence herbs
vitana rozmarin: rosemary
vitana ryze: rice
vitana tymian: thyme
vitana vanilka mleta: vanilla
vodka: vodka
water in a glass: water
watermelon: watermelon
whiskey: whiskey
white onion: white onion
white wine: white wine
worcester: worcestershire sauce
worcestershire sauce: worcestershire sauce
zakysana smetana: sour cream
zerve: cream cheese
zucchini: zucchini
